services:
  mysqldb:
    image: mysql
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
    ports:
      - "$MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT"
    networks:
      - backend
  
  app:
    build: .
    depends_on:
      - mysqldb
    links:
      - mysqldb
    ports:
      - "$NODE_LOCAL_PORT:$NODE_DOCKER_PORT"
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysqldb
    depends_on:
      - mysqldb
    restart: always
    ports:
      - 8080:80
    networks:
      - backend
networks:
  backend:
    name: backend